<2014-05-07 Wed 23:33>

unzip 
./mrtinstall


****************************************************
          * Congratulations! You have successfully installed *
          * the MODIS Reprojection Tool on your system!      *
          ****************************************************

                          IMPORTANT NOTICE!!!

The MRT bin directory has been added to the path for your account,
and the MRT_DATA_DIR environmental variable has been set to the
MRT data directory.  This has been accomplished by modifying the
startup files .login, .cshrc, .tcshrc, .profile, and/or .bash_profile
in your home directory. These changes will not take effect until you log
out and log back in again.

The .login, .cshrc, and .tcshrc files have the following lines appended:

    setenv MRT_HOME /home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT
    set path = ( $path /home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT/bin )
    setenv MRT_DATA_DIR /home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT/data

The .profile and .bash_profile files have the following lines appended:

    MRT_HOME=/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT
    PATH=$PATH:/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT/bin
    MRT_DATA_DIR=/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT/data
    export MRT_HOME PATH MRT_DATA_DIR



in .profile
# Wed May  7 23:32:09 JST 2014 - MODIS Reprojection Tool modifications
MRT_HOME="/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT"
PATH="$PATH:/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT/bin"
MRT_DATA_DIR="/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRT/data"
export MRT_HOME PATH MRT_DATA_DIR


* MRTSWATH
Press the Enter key to finish the MRTSwath installation.


          *****************************************************
          * Congratulations! You have successfully installed  *
          * the MODIS Reprojection Swath Tool on your system! *
          *****************************************************

                          IMPORTANT NOTICE!!!

The MRTSwath bin directory has been added to the path for your account,
and the MRTSWATH_DATA_DIR environmental variable has been set to the
 MRTSwath data directory.  This has been accomplished by modifying the
startup files .login, .cshrc, .tcshrc, .profile, and/or .bash_profile
in your home directory. These changes will not take effect until you log
out and log back in again.

The .login, .cshrc, and .tcshrc files have the following lines appended:

    setenv MRTSWATH_HOME /home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRTSwath
    set path = ( $path /home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRTSwath/bin )
    setenv MRTSWATH_DATA_DIR /home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRTSwath/data

The .profile and .bash_profile files have the following lines appended:

    MRTSWATH_HOME=/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRTSwath
    PATH=$PATH:/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRTSwath/bin
    MRTSWATH_DATA_DIR=/home/tian/Win7/Air/Dropbox/soft/linux/MRT/MRTSwath/data
    export MRTSWATH_HOME PATH MRTSWATH_DATA_DIR

